modLoader="javafml" 
loaderVersion="[38,)"
license="CC0"

[[mods]] 
modId="itemchat" 
version="${file.jarVersion}" 
displayName="Item Chat" 
logoFile="itemchat.png" 
credits="Feature from Quark (a mod by Vaskii)!" 
authors="Cy4" 

description='''
This mod adds a feature from Quark into a standalone mod.
'''

[[dependencies.itemchat]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.itemchat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2]"
    ordering="NONE"
    side="BOTH"
